#### [Microsoft.FactoryOrchestrator.Core](./Microsoft-FactoryOrchestrator-Core.md 'Microsoft.FactoryOrchestrator.Core')
### [Microsoft.FactoryOrchestrator.Core](./Microsoft-FactoryOrchestrator-Core.md 'Microsoft.FactoryOrchestrator.Core').[FactoryOrchestratorTaskListRunningException](./Microsoft-FactoryOrchestrator-Core-FactoryOrchestratorTaskListRunningException.md 'Microsoft.FactoryOrchestrator.Core.FactoryOrchestratorTaskListRunningException')
## FactoryOrchestratorTaskListRunningException(string, System.Exception) Constructor
Initializes a new instance of the [FactoryOrchestratorTaskListRunningException](./Microsoft-FactoryOrchestrator-Core-FactoryOrchestratorTaskListRunningException.md 'Microsoft.FactoryOrchestrator.Core.FactoryOrchestratorTaskListRunningException') class.  
```csharp
public FactoryOrchestratorTaskListRunningException(string message, System.Exception innerException);
```
#### Parameters
<a name='Microsoft-FactoryOrchestrator-Core-FactoryOrchestratorTaskListRunningException-FactoryOrchestratorTaskListRunningException(string_System-Exception)-message'></a>
`message` [System.String](https://docs.microsoft.com/en-us/dotnet/api/System.String 'System.String')  
The error message that explains the reason for the exception.  
  
<a name='Microsoft-FactoryOrchestrator-Core-FactoryOrchestratorTaskListRunningException-FactoryOrchestratorTaskListRunningException(string_System-Exception)-innerException'></a>
`innerException` [System.Exception](https://docs.microsoft.com/en-us/dotnet/api/System.Exception 'System.Exception')  
The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified.  
  
